// Barrel (gen/ts/index.ts) ve cok dosyali paketlerin package-index.ts'inin SAF
// uretimi (#135, D18): dosya okumaz, yazmaz; write-barrel.mjs cagirir, testler
// dogrudan dener.
//
// KURAL: ad alani klasorden gelir (proto paketi = klasor, PACKAGE_DIRECTORY_MATCH).
//   - Tek dosyali paket: export * as catalogV1 from "./getir/catalog/v1/catalog.js";
//   - Cok dosyali paket: klasore package-index.ts yazilir (dosyalarin hepsi
//     "export *"), barrel onu ad alani olarak verir. Ad tiresiz bir proto
//     dosyasindan (FILE_LOWER_SNAKE_CASE) URETILEMEZ: ts-proto ciktisiyla cakismaz.
//
// ORTAK ADLAR: ts-proto her dosyada ayni yardimcilari disa verir (HELPER_NAMES).
// "export *" iki kaynakta ayni adi BELIRSIZ birakir (TS2308); bu adlar onu disa
// veren alfabetik ilk dosyadan ACIKCA yeniden disa verilir. Yardimci DISINDA bir
// ad iki dosyada varsa (ayni mesaj iki .proto'da, ya da eski bir uretim kalintisi)
// uretim DURUR: sessizce birini secmek yanlis kodu derlenir birakirdi.
//
// DETERMINIZM: dosyalar, adlar ve ad alanlari kod birimi sirasiyla siralanir;
// ayni girdi bayt bayt ayni cikti verir (yerel ayara bagli localeCompare yok).

/**
 * @typedef {{ path: string, values: string[], types: string[] }} GeneratedFile
 *   path: gen/ts'e goreli, ileri bolulu yol ("getir/order/v1/order.ts").
 * @typedef {{ path: string, contents: string }} OutputFile
 */

/** Barrel: gen/ts kokundeki giris noktasi. */
export const BARREL_FILE = 'index.ts';

/** Cok dosyali paketin index dosyasinin adi. */
export const PACKAGE_INDEX_FILE = 'package-index.ts';

/** ts-proto'nun her dosyada disa verdigi yardimci adlar (deger ve tip). */
export const HELPER_NAMES = Object.freeze(['DeepPartial', 'MessageFns', 'protobufPackage']);

const HEADER = [
  '// Code generated by scripts/write-barrel.mjs. DO NOT EDIT.',
  '// Kaynak: packages/proto/proto/**/*.proto  |  Uretim: pnpm --filter @getir/proto generate:ts',
  '',
  '/* eslint-disable */',
];

/**
 * Klasor yolundan ad alani: "getir" org oneki atilir, parcalar camelCase.
 *   getir/catalog/v1 -> catalogV1;  google/protobuf -> googleProtobuf
 * @param {string} directory
 * @returns {string}
 */
export function namespaceOf(directory) {
  const segments = directory.split('/').filter((segment) => segment !== '');
  if (segments[0] === 'getir') segments.shift();
  return segments
    .map((segment, index) => (index === 0 ? segment : segment[0]?.toUpperCase() + segment.slice(1)))
    .join('');
}

/**
 * Dosyanin klasoru. Kokteki dosya (paketsiz proto) reddedilir: ad alani olmaz.
 * @param {string} path
 * @returns {string}
 */
export function directoryOf(path) {
  const slash = path.lastIndexOf('/');
  if (slash <= 0) {
    throw new Error(`Paketsiz uretilmis dosya: "${path}" (her proto bir paket klasorunde olmali).`);
  }
  return path.slice(0, slash);
}

/** @param {string} path */
function fileNameOf(path) {
  return path.slice(path.lastIndexOf('/') + 1);
}

/**
 * Bu uretimin kendi ciktisi mi (koktaki barrel ya da bir package-index.ts)?
 * Ciktilar girdiye alinmaz; alinsaydi ikinci kosuda paket index'i kendini disa
 * verirdi. Paket klasorundeki index.ts (index.proto ciktisi) girdidir.
 * @param {string} path gen/ts'e goreli yol
 * @returns {boolean}
 */
export function isBarrelOutput(path) {
  return path === BARREL_FILE || fileNameOf(path) === PACKAGE_INDEX_FILE;
}

/** @param {string} path ".ts" yolu -> ESM ".js" belirteci */
function jsSpecifier(path) {
  return path.replace(/\.ts$/, '.js');
}

/** @param {{ path: string }} a @param {{ path: string }} b */
function byPath(a, b) {
  return a.path < b.path ? -1 : a.path > b.path ? 1 : 0;
}

/**
 * Birden cok dosyanin disa verdigi adlar -> onu disa veren ilk dosya.
 * Yardimci disinda ortak ad varsa hata.
 * @param {GeneratedFile[]} sorted yola gore sirali
 * @param {'values' | 'types'} kind
 * @returns {Map<string, string>} ad -> kaynak dosya yolu
 */
function sharedSources(sorted, kind) {
  /** @type {Map<string, string[]>} */
  const owners = new Map();
  for (const file of sorted) {
    for (const name of file[kind]) {
      const paths = owners.get(name) ?? [];
      paths.push(file.path);
      owners.set(name, paths);
    }
  }
  /** @type {Map<string, string>} */
  const sources = new Map();
  for (const [name, paths] of [...owners].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))) {
    if (paths.length < 2) continue;
    if (!HELPER_NAMES.includes(name)) {
      throw new Error(
        `Ayni ad birden cok dosyada: "${name}" (${paths.join(', ')}). Eski uretim kalintisi olabilir: pnpm --filter @getir/proto clean.`,
      );
    }
    sources.set(name, paths[0] ?? '');
  }
  return sources;
}

/**
 * Ortak adlarin acik yeniden disa verilmesi: kaynak dosya basina tek satir.
 * @param {Map<string, string>} sources ad -> kaynak
 * @param {string} keyword "export" ya da "export type"
 * @returns {string[]}
 */
function explicitExports(sources, keyword) {
  /** @type {Map<string, string[]>} */
  const bySource = new Map();
  for (const [name, source] of sources) {
    const names = bySource.get(source) ?? [];
    names.push(name);
    bySource.set(source, names);
  }
  return [...bySource]
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(
      ([source, names]) =>
        `${keyword} { ${names.join(', ')} } from "./${jsSpecifier(fileNameOf(source))}";`,
    );
}

/**
 * Cok dosyali paketin package-index.ts'i.
 * @param {GeneratedFile[]} files ayni klasorde, EN AZ iki dosya
 * @returns {string}
 * @throws {Error} ikiden az dosya ya da yardimci disinda ortak ad
 */
export function renderPackageIndex(files) {
  if (files.length < 2) {
    throw new Error(`Paket index'i en az iki dosya ister (${files.length} verildi).`);
  }
  const sorted = [...files].sort(byPath);
  const values = sharedSources(sorted, 'values');
  const types = sharedSources(sorted, 'types');
  return [
    ...HEADER,
    ...sorted.map((file) => `export * from "./${jsSpecifier(fileNameOf(file.path))}";`),
    ...explicitExports(values, 'export'),
    ...explicitExports(types, 'export type'),
    '',
  ].join('\n');
}

/**
 * Barrel ve gerekiyorsa paket index'leri.
 * @param {GeneratedFile[]} files gen/ts altindaki uretilen dosyalar (barrel ve paket index'leri HARIC)
 * @returns {{ barrel: string, packageIndexes: OutputFile[] }}
 * @throws {Error} iki klasor ayni ad alanini uretirse; paketsiz dosya
 */
export function renderBarrel(files) {
  /** @type {Map<string, GeneratedFile[]>} */
  const packages = new Map();
  for (const file of [...files].sort(byPath)) {
    const directory = directoryOf(file.path);
    const members = packages.get(directory) ?? [];
    members.push(file);
    packages.set(directory, members);
  }

  /** @type {{ namespace: string, specifier: string }[]} */
  const entries = [];
  /** @type {OutputFile[]} */
  const packageIndexes = [];
  for (const [directory, members] of packages) {
    const only = members.length === 1 ? members[0] : undefined;
    if (only !== undefined) {
      entries.push({ namespace: namespaceOf(directory), specifier: `./${jsSpecifier(only.path)}` });
      continue;
    }
    const indexPath = `${directory}/${PACKAGE_INDEX_FILE}`;
    packageIndexes.push({ path: indexPath, contents: renderPackageIndex(members) });
    entries.push({ namespace: namespaceOf(directory), specifier: `./${jsSpecifier(indexPath)}` });
  }

  // Sirala, sonra cakismayi denetle: hata cumlesi de deterministik olsun.
  entries.sort((a, b) =>
    a.namespace < b.namespace
      ? -1
      : a.namespace > b.namespace
        ? 1
        : a.specifier < b.specifier
          ? -1
          : 1,
  );
  for (let index = 1; index < entries.length; index += 1) {
    const previous = entries[index - 1];
    const current = entries[index];
    if (
      previous !== undefined &&
      current !== undefined &&
      previous.namespace === current.namespace
    ) {
      throw new Error(
        `Ad alani cakismasi: "${current.namespace}" hem ${previous.specifier} hem ${current.specifier} tarafindan uretiliyor.`,
      );
    }
  }

  const barrel = [
    ...HEADER,
    ...entries.map(({ namespace, specifier }) => `export * as ${namespace} from "${specifier}";`),
    '',
  ].join('\n');
  return { barrel, packageIndexes };
}

const VALUE_EXPORT =
  /^export (?:declare )?(?:const enum|enum|const|let|var|async function\*?|function\*?|abstract class|class) ([A-Za-z_$][\w$]*)/gm;
const TYPE_EXPORT = /^export (?:declare )?(?:interface|type) ([A-Za-z_$][\w$]*)/gm;

/**
 * ts-proto ciktisindan disa verilen adlar. Deger: const/let/var/function/class/
 * enum (const enum dahil); tip: interface/type. Liste bicimi ("export { ... }")
 * ts-proto'da yok; cikarsa kacan ortak ad tsc'de TS2308 olarak gorunur.
 * @param {string} source
 * @returns {{ values: string[], types: string[] }}
 */
export function exportedNames(source) {
  const names = (/** @type {RegExp} */ pattern) =>
    [...new Set([...source.matchAll(pattern)].map((match) => match[1] ?? ''))].sort();
  return { values: names(VALUE_EXPORT), types: names(TYPE_EXPORT) };
}
