// gen/ts/index.ts dosyasini uretir: paketin tek giris noktasi.
//
// NEDEN ELLE YAZILMIYOR: index dosyasi .proto listesini birebir izlemek zorunda.
// Elle tutulsaydi yeni bir proto eklendiginde unutulur ve eksiklik ancak baska bir
// serviste "export yok" hatasi olarak ortaya cikardi.
//
// NEDEN ts-proto'nun "outputIndex=true" secenegi KULLANILMIYOR: o secenek her proto
// paketi icin ayri bir index uretir (index.getir.catalog.v1.ts, index.getir.catalog.ts,
// ...) ve ust seviyelerde ayni dosya adini iki kez uretip buf'ta
// "duplicate generated file name" uyarisi verir. Tek ve duz bir giris noktasi istiyoruz.
//
// NEDEN DUZ "export *" DEGIL, AD ALANI: her uretilen dosya "protobufPackage" adli bir
// sabit disari verir. Duz "export *" ile yedi dosyanin yedisi ayni adi verir ve
// derleme cakisma yuzunden kirilir. Ayrica Money/GeoPoint gibi tipler birden cok
// dosyadan yeniden disari verilebilir. "export * as commonV1" bu sinifin tamamini
// kokten cozer ve cagri yerinde hangi sozlesmeden geldigi okunur olur:
//     import { catalogV1 } from '@getir/proto';
//     const client = new catalogV1.CatalogServiceClient(...);

import { readdirSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const PACKAGE_ROOT = fileURLToPath(new URL('..', import.meta.url));
const GEN_TS_DIR = join(PACKAGE_ROOT, 'gen', 'ts');
const BARREL_PATH = join(GEN_TS_DIR, 'index.ts');

/** Uretilen .ts dosyalarini gen/ts altinda ozyinelemeli tarar. */
function collectGeneratedFiles(directory) {
  const found = [];
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const fullPath = join(directory, entry.name);
    if (entry.isDirectory()) {
      found.push(...collectGeneratedFiles(fullPath));
    } else if (entry.name.endsWith('.ts') && fullPath !== BARREL_PATH) {
      found.push(fullPath);
    }
  }
  return found;
}

/**
 * Dosya yolundan ad alani adi turetir. Kural, dosya ADINI degil KLASORUNU kullanir;
 * cunku klasor yolu proto paket adinin birebir karsiligidir (PACKAGE_DIRECTORY_MATCH).
 *
 *   getir/catalog/v1/catalog.ts   -> catalogV1      ("getir" org onekidir, atilir)
 *   getir/common/v1/common.ts     -> commonV1
 *   google/protobuf/timestamp.ts  -> googleProtobuf
 */
function toNamespace(relativePath) {
  const segments = relativePath.split(sep).slice(0, -1);
  if (segments[0] === 'getir') segments.shift();
  return segments
    .map((segment, index) => (index === 0 ? segment : segment[0].toUpperCase() + segment.slice(1)))
    .join('');
}

const modules = collectGeneratedFiles(GEN_TS_DIR)
  .map((fullPath) => {
    const relativePath = relative(GEN_TS_DIR, fullPath);
    return {
      namespace: toNamespace(relativePath),
      // ESM: import yolu uzantili ve ileri bolu isaretli olmak zorunda.
      specifier: `./${relativePath.split(sep).join('/').replace(/\.ts$/, '.js')}`,
    };
  })
  .sort((a, b) => a.namespace.localeCompare(b.namespace));

// Iki proto dosyasi ayni klasore konursa ayni ad alanini uretirler ve biri
// digerini sessizce golgelerdi. Sessiz kalmaktansa burada duruyoruz.
const seen = new Map();
for (const { namespace, specifier } of modules) {
  const previous = seen.get(namespace);
  if (previous) {
    throw new Error(
      `Ad alani cakismasi: "${namespace}" hem ${previous} hem ${specifier} tarafindan uretiliyor. ` +
        'Her proto paketi (klasor) tek bir .proto dosyasi icermelidir.',
    );
  }
  seen.set(namespace, specifier);
}

const contents = [
  '// Code generated by scripts/write-barrel.mjs. DO NOT EDIT.',
  '// Kaynak: packages/proto/proto/**/*.proto  |  Uretim: pnpm --filter @getir/proto generate:ts',
  '',
  '/* eslint-disable */',
  ...modules.map(({ namespace, specifier }) => `export * as ${namespace} from "${specifier}";`),
  '',
].join('\n');

writeFileSync(BARREL_PATH, contents, 'utf8');
console.log(`gen/ts/index.ts yazildi (${modules.length} modul).`);
