// Code generated by packages/contracts/scripts/write-go-error-codes.mjs. DO NOT EDIT.
//
// Kaynak: @getir/core/error-codes.ts (kod -> HTTP) ve @getir/contracts/errors.ts
// (kod -> kullanici mesaji). Degistirmek icin kaynagi duzenleyip "pnpm codes:go"
// calistirin; CI "pnpm codes:go:check" ile farki yakalar.

package apperror

// CodeValidationFailed = VALIDATION_FAILED.
const CodeValidationFailed Code = "VALIDATION_FAILED"

// CodeUnauthorized = UNAUTHORIZED.
const CodeUnauthorized Code = "UNAUTHORIZED"

// CodeForbidden = FORBIDDEN.
const CodeForbidden Code = "FORBIDDEN"

// CodeNotFound = NOT_FOUND.
const CodeNotFound Code = "NOT_FOUND"

// CodeConflict = CONFLICT.
const CodeConflict Code = "CONFLICT"

// CodeInternal = INTERNAL.
const CodeInternal Code = "INTERNAL"

// CodeStockInsufficient = STOCK_INSUFFICIENT.
const CodeStockInsufficient Code = "STOCK_INSUFFICIENT"

// CodeReservationExpired = RESERVATION_EXPIRED.
const CodeReservationExpired Code = "RESERVATION_EXPIRED"

// CodeReservationActive = RESERVATION_ACTIVE.
const CodeReservationActive Code = "RESERVATION_ACTIVE"

// CodeRiskBlocked = RISK_BLOCKED.
const CodeRiskBlocked Code = "RISK_BLOCKED"

// CodeRiskReview = RISK_REVIEW.
const CodeRiskReview Code = "RISK_REVIEW"

// CodePaymentDeclined = PAYMENT_DECLINED.
const CodePaymentDeclined Code = "PAYMENT_DECLINED"

// CodeThreedsFailed = THREEDS_FAILED.
const CodeThreedsFailed Code = "THREEDS_FAILED"

// CodePriceChanged = PRICE_CHANGED.
const CodePriceChanged Code = "PRICE_CHANGED"

// CodeCouponInvalid = COUPON_INVALID.
const CodeCouponInvalid Code = "COUPON_INVALID"

// CodeMinBasketNotMet = MIN_BASKET_NOT_MET.
const CodeMinBasketNotMet Code = "MIN_BASKET_NOT_MET"

// CodeNoStore = NO_STORE.
const CodeNoStore Code = "NO_STORE"

// CodeRequestInProgress = REQUEST_IN_PROGRESS.
const CodeRequestInProgress Code = "REQUEST_IN_PROGRESS"

// CodeRateLimited = RATE_LIMITED.
const CodeRateLimited Code = "RATE_LIMITED"

// CodeOrderStateInvalid = ORDER_STATE_INVALID.
const CodeOrderStateInvalid Code = "ORDER_STATE_INVALID"

// CodeThreedsRequired = THREEDS_REQUIRED.
const CodeThreedsRequired Code = "THREEDS_REQUIRED"

// CodeServiceUnavailable = SERVICE_UNAVAILABLE.
const CodeServiceUnavailable Code = "SERVICE_UNAVAILABLE"

// codeTable, her kodun HTTP karsiligi ve kullanici mesaji.
var codeTable = []codeEntry{
	{code: CodeValidationFailed, httpStatus: 400, message: "Girdiğin bilgilerde bir sorun var, kontrol eder misin?"},
	{code: CodeUnauthorized, httpStatus: 401, message: "Oturumun sona ermiş. Tekrar giriş yapman gerekiyor."},
	{code: CodeForbidden, httpStatus: 403, message: "Bu işlem için yetkin yok."},
	{code: CodeNotFound, httpStatus: 404, message: "Aradığın kaydı bulamadık."},
	{code: CodeConflict, httpStatus: 409, message: "Bu kayıt az önce değişti. Sayfayı yenileyip tekrar dener misin?"},
	{code: CodeInternal, httpStatus: 500, message: "Beklenmeyen bir sorun oldu. Birazdan tekrar dene."},
	{code: CodeStockInsufficient, httpStatus: 409, message: "Bu üründen yeterli stok kalmadı."},
	{code: CodeReservationExpired, httpStatus: 410, message: "Süre doldu, sepetini yenileyelim."},
	{code: CodeReservationActive, httpStatus: 409, message: "Devam eden bir siparişin var. Önce onu tamamla ya da iptal et."},
	{code: CodeRiskBlocked, httpStatus: 403, message: "Bu siparişi şu an tamamlayamıyoruz. Destek ekibimizle görüşebilirsin."},
	{code: CodeRiskReview, httpStatus: 202, message: "Siparişin kontrol ediliyor. Sonucu birazdan bildireceğiz."},
	{code: CodePaymentDeclined, httpStatus: 402, message: "Ödeme alınamadı. Başka bir kart deneyebilirsin."},
	{code: CodeThreedsFailed, httpStatus: 402, message: "Doğrulama kodu geçersiz. Tekrar dener misin?"},
	{code: CodePriceChanged, httpStatus: 409, message: "Sepetindeki fiyatlar güncellendi. Yeni tutarı onaylar mısın?"},
	{code: CodeCouponInvalid, httpStatus: 422, message: "Bu kupon kullanılamıyor."},
	{code: CodeMinBasketNotMet, httpStatus: 422, message: "Minimum sepet tutarına ulaşmadın."},
	{code: CodeNoStore, httpStatus: 404, message: "Bu adrese şu anda teslimat yapamıyoruz."},
	{code: CodeRequestInProgress, httpStatus: 409, message: "İşlemin sürüyor, biraz bekler misin?"},
	{code: CodeRateLimited, httpStatus: 429, message: "Çok fazla deneme yaptın. Kısa bir süre sonra tekrar dene."},
	{code: CodeOrderStateInvalid, httpStatus: 409, message: "Siparişin bu adımda bu işlemi yapmaya uygun değil."},
	{code: CodeThreedsRequired, httpStatus: 402, message: "Ödemeyi tamamlamak için doğrulama kodunu girmen gerekiyor."},
	{code: CodeServiceUnavailable, httpStatus: 503, message: "Servise şu an ulaşamıyoruz. Birazdan tekrar dene."},
}
