/**
 * Go hata kodu ureteci (D5'te kok scripts/'e tasindi): sabit adlari, tablo
 * satirlari ve depodaki uretilmis dosyanin guncelligi.
 */

import { readFileSync } from 'node:fs';

import { ERROR_MESSAGES } from '@getir/contracts';
import { ERROR_CODES, httpStatusFor } from '@getir/core';
import { describe, expect, it } from 'vitest';

import { goConstName, OUTPUT_PATH, render } from '../write-go-error-codes.mjs';

describe('goConstName', () => {
  it.each([
    ['VALIDATION_FAILED', 'CodeValidationFailed'],
    ['NOT_IMPLEMENTED', 'CodeNotImplemented'],
    ['THREEDS_REQUIRED', 'CodeThreedsRequired'],
  ])('%s -> %s', (code, name) => {
    expect(goConstName(code)).toBe(name);
  });
});

describe('render', () => {
  const output = render();

  it('her kod icin sabit ve HTTP durumu + mesajla tablo satiri yazar', () => {
    for (const code of Object.values(ERROR_CODES)) {
      expect(output).toContain(`const ${goConstName(code)} Code = "${code}"`);
      expect(output).toContain(
        `{code: ${goConstName(code)}, httpStatus: ${httpStatusFor(code)}, message: ${JSON.stringify(ERROR_MESSAGES[code])}},`,
      );
    }
  });

  it('uretici olarak kok scripts/ yolunu yazar (packages apps yolunu bilmez)', () => {
    expect(output.split('\n')[0]).toBe(
      '// Code generated by scripts/write-go-error-codes.mjs. DO NOT EDIT.',
    );
    expect(OUTPUT_PATH.endsWith('apps/gateway/internal/apperror/codes_gen.go')).toBe(true);
  });

  it('depodaki codes_gen.go guncel ("pnpm codes:go:check" ile ayni denetim)', () => {
    expect(readFileSync(OUTPUT_PATH, 'utf8')).toBe(output);
  });
});
