import type { PaymentMethodsContent } from './payment-methods.js';

/**
 * Odeme Yontemlerim'in yedegi (T11.17): icerik gelmese de kartlar listelenir,
 * eklenir ve silinir. Kural cumleleri sozlesmede (CARD_FIELD_MESSAGES).
 */
export const PAYMENT_METHODS_FALLBACK: PaymentMethodsContent = {
  title: 'Ödeme Yöntemlerim',
  loadingLabel: 'Kartların yükleniyor…',
  addLabel: 'Kredi/Banka Kartı',
  expiredLabel: 'Süresi doldu',
  lastFourLabel: 'son dört hane',
  deleteSuffix: 'kartını sil',
  confirmQuestion: 'Kartı silmek istediğinden emin misin?',
  deletingLabel: 'Siliniyor…',
  deletedToastSuffix: 'kartı silindi.',
  closeLabel: 'Kapat',
  backToListLabel: "Ödeme Yöntemlerim'e geri dön",
  addTitle: 'Kart Ekle',
  securityTitle: 'Güvenlik',
  securityText:
    "Kart numaranın tamamını ve CVV'ni saklamıyoruz; yalnızca ilk 4 ve son 4 hane saklanır. Kartını istediğin zaman silebilirsin.",
  nicknameLabel: 'Karta İsim Ver (Kişisel, İş vb.)',
  numberLabel: 'Kart Numarası',
  numberValidLabel: 'Geçerli kart numarası',
  holderNameLabel: 'Kart Üzerindeki İsim',
  expiryLegend: 'Kartın Son Kullanma Tarihi:',
  monthLabel: 'Ay',
  yearLabel: 'Yıl',
  expiryRequiredNotice: 'Son kullanma ayını ve yılını seç',
  cvvLabel: 'CVV',
  termsLinkLabel: 'Kullanım Koşulları',
  termsSuffix: "'nı okudum, kabul ediyorum.",
  termsRequiredNotice: 'Devam etmek için kullanım koşullarını kabul et',
  termsTitle: 'Kart saklama koşulları',
  termsParagraphs: [
    'Kart numaranın tamamı ve CVV saklanmaz. Kartının yalnızca ilk 4 ve son 4 hanesi, markası, son kullanma tarihi ve üzerindeki isim saklanır.',
    'Kartın kaydedilmeden önce ödeme sağlayıcısında 0 TL tutarında doğrulanır; bu doğrulama hesabından para çekmez.',
    "Bir hesapta en fazla 10 kart kayıtlı olabilir. Kayıtlı kartlarını Ödeme Yöntemlerim'den istediğin zaman silebilirsin.",
    'Son kullanma tarihi geçen kart listede kalır ama ödemede kullanılmaz.',
  ],
  saveLabel: 'Devam',
  savingLabel: 'Kaydediliyor…',
  retryWaitLabel: 'Yeniden deneyebilmen için',
  duplicateCardNotice: 'Bu kart zaten kayıtlı.',
  addedToastPrefix: 'Kart eklendi:',
  acceptedBrandsLabel: 'Kabul edilen kartlar',
  holderCaption: 'KART SAHİBİ',
  expiryCaption: 'SKT',
  holderPlaceholder: 'AD SOYAD',
  expiryPlaceholder: 'AA/YY',
  nicknamePlaceholder: 'Kartım',
  cvvCaption: 'CVV',
  cvvNote: 'CVV yalnızca doğrulama için kullanılır, saklanmaz.',
  brandLabels: { VISA: 'Visa', MASTERCARD: 'Mastercard', AMEX: 'Amex', TROY: 'Troy' },
  brandMarks: { VISA: 'VISA', MASTERCARD: 'MC', AMEX: 'AMEX', TROY: 'troy' },
};
